reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
max_width = 100
edition = "2021"
chain_width = 80
tab_spaces = 4
newline_style = "Unix"
single_line_if_else_max_width = 50
fn_params_layout = "Tall"
control_brace_style = "AlwaysSameLine"